AWSTemplateFormatVersion: '2010-09-09'
Description: "Create webAcl"

Parameters:
  AppEnvironment:
    Description: Type of app environment.
    Type: String
    Default: staging
    AllowedValues:
      - staging
      - production
  KinesisDeliveryStreamArn:
    Description: Type of Kinesis Firehose arn for WAF Log
    Type: String

Resources:
# ------------------------------------------------------------#
# AWS WAFv2
# ------------------------------------------------------------#
  WebAclCloudFront:
    Type: AWS::WAFv2::WebACL
    Properties:
      DefaultAction:
        Allow: {}
      Description: WebACL for CloudFront
      Name: !Sub ${AppEnvironment}-cfj-decidim-web-acl
      Rules:
        - Name: !Sub ${AppEnvironment}-AWSManagedRulesCommonRuleSet
          Priority: 0
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedRulesCommonRuleSetMetric
          Statement:
            ManagedRuleGroupStatement:
              ExcludedRules:
                - Name: CrossSiteScripting_BODY
                - Name: SizeRestrictions_BODY
                - Name: GenericRFI_BODY
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
        - Name: !Sub ${AppEnvironment}-AWSManagedRulesKnownBadInputsRuleSet
          Priority: 1
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedRulesKnownBadInputsRuleSetMetric
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesKnownBadInputsRuleSet
        - Name: !Sub ${AppEnvironment}-AWSManagedRulesAmazonIpReputationList
          Priority: 2
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedRulesAmazonIpReputationListMetric
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesAmazonIpReputationList
        - Name: !Sub ${AppEnvironment}-AWSManagedRulesLinuxRuleSet
          Priority: 3
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedRulesLinuxRuleSetMetric
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesLinuxRuleSet
        - Name: !Sub ${AppEnvironment}-AWSManagedRulesSQLiRuleSet
          Priority: 4
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedRulesSQLiRuleSetMetric
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesSQLiRuleSet
      Scope: CLOUDFRONT
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: !Sub ${AppEnvironment}-cfj-decidim-web-acl
  WafLoggingConfig:
    Type: AWS::WAFv2::LoggingConfiguration
    Properties:
      LogDestinationConfigs:
        - !Sub ${KinesisDeliveryStreamArn}
      RedactedFields:
        - SingleHeader: { Name: cookie }
      ResourceArn: !Sub "${WebAclCloudFront.Arn}"
      LoggingFilter:
        DefaultBehavior: DROP
        Filters:
          - Behavior: KEEP
            Conditions:
              - ActionCondition:
                  Action: BLOCK
              - ActionCondition:
                  Action: COUNT
            Requirement: MEETS_ANY
