# frozen_string_literal: true

# Until the upstream Rails upgrade lands (Decidim 0.30 / Rails 7.1+),
# we filter the decoded Hash down to the transformation methods that
# Rails 7.1.5.2 ships as `ActiveStorage.supported_image_processing_methods`
# (with `apply` / `loader` / `saver` explicitly excluded).
module BlobRendererHardening
  # Mirrors ActiveStorage.supported_image_processing_methods from Rails v7.1.5.2.
  # Kept as a frozen Set of strings to allow O(1) key lookup while preserving parity with the upstream fix.
  # rubocop:disable Metrics/CollectionLiteralLength
  ALLOWED_VARIATION_KEYS = %w(
    adaptive_blur
    adaptive_resize
    adaptive_sharpen
    adjoin
    affine
    alpha
    annotate
    antialias
    append
    attenuate
    authenticate
    auto_gamma
    auto_level
    auto_orient
    auto_threshold
    backdrop
    background
    bench
    bias
    bilateral_blur
    black_point_compensation
    black_threshold
    blend
    blue_primary
    blue_shift
    blur
    border
    bordercolor
    borderwidth
    brightness_contrast
    cache
    canny
    caption
    channel
    channel_fx
    charcoal
    chop
    clahe
    clamp
    clip
    clip_path
    clone
    clut
    coalesce
    colorize
    colormap
    color_matrix
    colors
    colorspace
    colourspace
    color_threshold
    combine
    combine_options
    comment
    compare
    complex
    compose
    composite
    compress
    connected_components
    contrast
    contrast_stretch
    convert
    convolve
    copy
    crop
    cycle
    deconstruct
    define
    delay
    delete
    density
    depth
    descend
    deskew
    despeckle
    direction
    displace
    dispose
    dissimilarity_threshold
    dissolve
    distort
    dither
    draw
    duplicate
    edge
    emboss
    encoding
    endian
    enhance
    equalize
    evaluate
    evaluate_sequence
    extent
    extract
    family
    features
    fft
    fill
    filter
    flatten
    flip
    floodfill
    flop
    font
    foreground
    format
    frame
    function
    fuzz
    fx
    gamma
    gaussian_blur
    geometry
    gravity
    grayscale
    green_primary
    hald_clut
    highlight_color
    hough_lines
    iconGeometry
    iconic
    identify
    ift
    illuminant
    immutable
    implode
    insert
    intensity
    intent
    interlace
    interline_spacing
    interpolate
    interpolative_resize
    interword_spacing
    kerning
    kmeans
    kuwahara
    label
    lat
    layers
    level
    level_colors
    limit
    limits
    linear_stretch
    linewidth
    liquid_rescale
    list
    log
    loop
    lowlight_color
    magnify
    map
    mattecolor
    median
    mean_shift
    metric
    mode
    modulate
    moments
    monitor
    monochrome
    morph
    morphology
    mosaic
    motion_blur
    name
    negate
    noise
    normalize
    opaque
    ordered_dither
    orient
    page
    paint
    pause
    perceptible
    ping
    pointsize
    polaroid
    poly
    posterize
    precision
    preview
    process
    quality
    quantize
    quiet
    radial_blur
    raise
    random_threshold
    range_threshold
    red_primary
    regard_warnings
    region
    remote
    render
    repage
    resample
    resize
    resize_to_fill
    resize_to_fit
    resize_to_limit
    resize_and_pad
    respect_parentheses
    reverse
    roll
    rotate
    sample
    sampling_factor
    scale
    scene
    screen
    seed
    segment
    selective_blur
    separate
    sepia_tone
    shade
    shadow
    shared_memory
    sharpen
    shave
    shear
    sigmoidal_contrast
    silent
    similarity_threshold
    size
    sketch
    smush
    snaps
    solarize
    sort_pixels
    sparse_color
    splice
    spread
    statistic
    stegano
    stereo
    storage_type
    stretch
    strip
    stroke
    strokewidth
    style
    subimage_search
    swap
    swirl
    synchronize
    taint
    text_font
    threshold
    thumbnail
    tile_offset
    tint
    title
    transform
    transparent
    transparent_color
    transpose
    transverse
    treedepth
    trim
    type
    undercolor
    unique_colors
    units
    unsharp
    update
    valid_image
    view
    vignette
    virtual_pixel
    visual
    watermark
    wave
    wavelet_denoise
    weight
    white_balance
    white_point
    white_threshold
    window
    window_group
  ).to_set.freeze
  # rubocop:enable Metrics/CollectionLiteralLength

  protected

  def blob_url(blob, variation = nil)
    super(blob, sanitize_variation(variation))
  end

  def local_blob_url(blob, variation = nil)
    super(blob, sanitize_variation(variation))
  end

  private

  def sanitize_variation(variation)
    return variation unless variation.is_a?(Hash)

    variation.select { |key, _| ALLOWED_VARIATION_KEYS.include?(key.to_s) }
  end
end

Rails.application.config.to_prepare do
  Decidim::ContentRenderers::BlobRenderer.prepend(BlobRendererHardening)
end
