name: Lint

on:
  push:
    branches:
    - master
    - develop
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: apt-get
      run: |
        sudo apt-get update -y
        sudo apt-get -yqq install libpq-dev postgresql-client
    - name: Set up Ruby 2.7
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true
    - name: Lint by RuboCop
      run: |
        bundle exec rubocop --parallel
